name = "Reki"
description = "CyborgWizard Vtuber"
keywords = "Reki, vtuber, gamer, youtube, twitch, cyborg, ENVtuber, streamer, carrd, linktree"
image = "rekinew.webp"
theme = "dark"
primary_color = "#42f5bf"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Links"
description = "Here are some of my Social Links"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/iVzYME0DbwI?si=KqksKtcsx9Fr7lfd"
[[sections.items]]
title = "Twitch"
description = "Twitch Affiliate"
icon = "https://cdn.simpleicons.org/twitch/ffffff"
url = "https://www.twitch.tv/reki_vt"
[[sections.items]]
title = "Youtube"
icon = "https://cdn.simpleicons.org/youtube/ffffff"
description = "Shorts, Streams and Videos"
url = "https://www.youtube.com/@getreki"
[[sections.items]]
title = "Reki's Discord"
icon = "https://cdn.simpleicons.org/discord/ffffff"
description = "My Discord Channel for Vtubing"
url = "https://discord.gg/DgFA3vzR8z"
[[sections.items]]
title = "Twitter"
icon = "https://cdn.simpleicons.org/x/ffffff"
description = "Ain't it called X"
url = "https://x.com/reki_vt"
[[sections.items]]
title = "Instagram"
icon = "https://cdn.simpleicons.org/instagram/ffffff"
description = "My Photography here"
url = "https://www.instagram.com/reki_vt"
[[sections.items]]
title = "VGen"
icon = "https://help.vgen.co/hc/article_attachments/13004249258519"
description = "VGen Page"
url = "https://vgen.co/JetJL/characters"
[[sections.items]]
title = "Blue Sky"
icon = "https://cdn.simpleicons.org/bluesky/ffffff"
description = "Nothing but"
url = "https://bsky.app/profile/reki-vt.bsky.social"
[[sections.items]]
title = " Bronco Esports Discord"
icon = "https://cdn.simpleicons.org/discord/ffffff"
description = "My Collegiate Esports Discord"
url = "https://discord.gg/UGBv2rw"

[[sections]]
title = "Others"
description = "Look for me on these other sites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/vrchat/ffffff"
title = "VrChat"
url = "https://vrchat.com/home/user/usr_246ae639-2c76-47df-a2d6-3f5b26ddc56e"
[[sections.items]]
icon = "https://cdn.simpleicons.org/printables/ffffff"
title = "Printables"
url = "https://www.printables.com/@JeTJL_267044"
[[sections.items]]
title = "Vroid"
url = "https://hub.vroid.com/en/characters/726736620083897447"
#[[sections.items]]
#icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
#title = "Wikipedia"
#url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
#[[sections.items]]
#title = "Rotten Tomatoes"
#icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
#url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
